# Generated by Django 6.1.1 on 2026-09-05 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carbs_pct',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_calorie_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fat_pct',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_weight_kg',
            field=models.FloatField(blank=True, help_text='Target weight, distinct from current weight_kg', null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(400.0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_pct',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='profile',
            name='sugar_goal_g',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
