# Generated by Django 6.1.1 on 2026-09-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_profile_current_streak_profile_last_active_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.TextField(blank=True, help_text='Base64 or URL profile image', null=True),
        ),
    ]
